#import "TiktigerPrefs.h"
@interface TTSettingsController:UIViewController<UITableViewDelegate,UITableViewDataSource>
@property(nonatomic,strong) UITableView *table; @property(nonatomic,strong) NSArray *sections; @property(nonatomic) BOOL arabic;
@end
@implementation TTSettingsController
- (void)viewDidLoad{ [super viewDidLoad]; self.sections=TTFeatureSections(); if(TTBool(@"developerTelegram")||TTBool(@"builtBy")){ self.view.accessibilityHint=@"Built with ❤️ by @ucorc — Telegram"; } self.arabic=![[NSUserDefaults standardUserDefaults] boolForKey:@"Tiktiger.english"]; self.view.backgroundColor=[UIColor colorWithWhite:.045 alpha:1]; self.table=[[UITableView alloc] initWithFrame:self.view.bounds style:UITableViewStyleGrouped]; self.table.autoresizingMask=UIViewAutoresizingFlexibleWidth|UIViewAutoresizingFlexibleHeight; self.table.backgroundColor=UIColor.clearColor; self.table.delegate=self; self.table.dataSource=self; [self.view addSubview:self.table]; UIButton *close=[UIButton buttonWithType:UIButtonTypeSystem]; close.frame=CGRectMake(12,42,44,42); [close setTitle:@"×" forState:UIControlStateNormal]; close.titleLabel.font=[UIFont systemFontOfSize:32 weight:UIFontWeightLight]; [close addTarget:self action:@selector(close) forControlEvents:UIControlEventTouchUpInside]; [self.view addSubview:close]; UIButton *language=[UIButton buttonWithType:UIButtonTypeSystem]; language.frame=CGRectMake(self.view.bounds.size.width-60,42,44,42); language.autoresizingMask=UIViewAutoresizingFlexibleLeftMargin; [language setImage:[UIImage systemImageNamed:@"globe"] forState:UIControlStateNormal]; [language addTarget:self action:@selector(language) forControlEvents:UIControlEventTouchUpInside]; [self.view addSubview:language]; UILabel *title=[[UILabel alloc] initWithFrame:CGRectMake(60,40,self.view.bounds.size.width-120,44)]; title.autoresizingMask=UIViewAutoresizingFlexibleWidth; title.text=@"⚡ Tiktiger 1.1"; title.textAlignment=NSTextAlignmentCenter; title.textColor=UIColor.yellowColor; title.font=[UIFont systemFontOfSize:20 weight:UIFontWeightBold]; [self.view addSubview:title]; self.table.contentInset=UIEdgeInsetsMake(75,0,20,0); }
- (NSInteger)numberOfSectionsInTableView:(UITableView *)t{return self.sections.count;}
- (NSInteger)tableView:(UITableView *)t numberOfRowsInSection:(NSInteger)s{return [self.sections[s][@"rows"] count];}
- (NSString *)tableView:(UITableView *)t titleForHeaderInSection:(NSInteger)s{return self.sections[s][@"title"];}
- (UITableViewCell *)tableView:(UITableView *)t cellForRowAtIndexPath:(NSIndexPath *)p{ NSArray *r=self.sections[p.section][@"rows"][p.row]; UITableViewCell *c=[[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:nil]; c.backgroundColor=[UIColor colorWithWhite:.105 alpha:.95]; c.textLabel.text=r[self.arabic?1:2]; c.textLabel.textColor=UIColor.whiteColor; c.imageView.image=[UIImage systemImageNamed:r[3]]; c.imageView.tintColor=[UIColor colorWithRed:.18 green:.55 blue:1 alpha:1]; UISwitch *sw=[UISwitch new]; sw.onTintColor=[UIColor colorWithRed:.13 green:.75 blue:.30 alpha:1]; sw.on=TTBool(r[0]); sw.tag=(p.section<<16)|p.row; [sw addTarget:self action:@selector(changed:) forControlEvents:UIControlEventValueChanged]; c.accessoryView=sw; return c; }
- (void)changed:(UISwitch *)s{ NSInteger sec=s.tag>>16,row=s.tag&0xffff; TTSetBool(self.sections[sec][@"rows"][row][0],s.isOn); }
- (void)language{ [[NSUserDefaults standardUserDefaults]setBool:self.arabic forKey:@"Tiktiger.english"]; self.arabic=!self.arabic; [UIView transitionWithView:self.table duration:.25 options:UIViewAnimationOptionTransitionCrossDissolve animations:^{[self.table reloadData];} completion:nil]; }
- (void)close{ [self dismissViewControllerAnimated:YES completion:nil]; }
@end
void TTShowSettings(UIViewController *presenter){ TTSettingsController *vc=[TTSettingsController new]; vc.modalPresentationStyle=UIModalPresentationPageSheet; vc.modalTransitionStyle=UIModalTransitionStyleCoverVertical; [presenter presentViewController:vc animated:YES completion:nil]; }
